### ISSUE TITLE
Error when attempting Scan()

### ISSUE THREAD

**Issue by ciehanski** [VirusTotal/vt-go#11]
I get the error: ```'unicode' object has no attribute 'type_options'```

An example of my code can be found below:
```go
// create new client from VT API key
client := vt.NewClient(*apiKey)
fs := client.NewFileScanner()

// open file to send for scan
file, err := os.Open(os.Args[2])
if err != nil {
	log.Fatalf("[vtotal] error opening file: %v", err)
}

// upload file to VT
var uploadProgress chan float32
vtObj, err := fs.Scan(file, "", uploadProgress)
if err != nil {
	log.Fatalf("[vtotal] error scanning file: %v", err)
}
```

**Comment by plusvic** [comment]
It looks like a backend issue, we are looking into it.

**Comment by plusvic** [comment]
The issue is triggered by the empty file name (second argument to `Scan`), with a non-empty string it works fine, but I think an empty string should be acceptable.

**Comment by ciehanski** [comment]
It seems as if the blank filename could have been the primary issue.
