### ISSUE TITLE
Default client requests marked as unknown

### ISSUE THREAD

**Issue by fcosantos** [VirusTotal/vt-go#13]
`userAgent: "unknown; vtgo 0.3; gzip"`

**Comment by plusvic** [comment]
That's the intended behavior. By setting the `Agent` field in `Client` (https://godoc.org/github.com/VirusTotal/vt-go#Client) users of the library can specify some string that identifies their application. If this is not set, "unknown" is used instead. But you still see that the request comes from `vt-go`, it's just that you don't know which application it is.

**Comment by 260498** [comment]
https://github.com/VirusTotal/vt-go/issues/13#issue-659121161
