### ISSUE TITLE
 receiving multiple 404 errors in a row for consecutive batches

### ISSUE THREAD

**Issue by Allyin** [VirusTotal/vt-go#34]
I mannual patch missingPackagesTolerance and found this title bug.

<img width="719" alt="image" src="https://github.com/VirusTotal/vt-go/assets/88423086/8a446dbb-92b6-4f35-bc91-868b41b23954">
<img width="1058" alt="image" src="https://github.com/VirusTotal/vt-go/assets/88423086/23549003-03d6-4318-a2e5-b85be815aa9d">
when occur this bug, the Feed retrieve processor will be terminated, is this expected?

If it's as expected, can I consider this is a bug in the vt data source?

**Comment by mgmacias95** [comment]
Hello @Allyin,

Which feed exactly are you downloading? Files, URLs, domains, IP addresses....
