### ISSUE TITLE
API failures due to quota limits raise confusing errors

### ISSUE THREAD

**Issue by sjacksonsplunk** [VirusTotal/vt-go#35]
If the example code in the README is run using an API key that is out of quota, the error raised from `vt.Client.GetObject` is unhelpful:

```
gzip: invalid header
```

This error is not of type `vt.Error,` so it's not readily captured by client code that is prepared to respond to VT API errors.

**Comment by mgmacias95** [comment]
Hello @sjacksonsplunk,

We have released a new version fixing this bug here: https://github.com/VirusTotal/vt-go/releases/tag/v1.0.1

I hope it helps.

Regards,
Marta

**Comment by sjacksonsplunk** [comment]
Thank you, we appreciate the prompt fix!
