### ISSUE TITLE
Failed to import module

### ISSUE THREAD

**Issue by Zachdehooge** [VirusTotal/vt-go#37]
<img width="1010" alt="Screenshot 2024-05-02 at 5 49 17 PM" src="https://github.com/VirusTotal/vt-go/assets/47896974/0df72a33-3bc4-49c7-afa4-fcfff75f1d87">

**Comment by plusvic** [comment]
You need to install the Go package with `go get github.com/VirusTotal/vt-go`

**Comment by Zachdehooge** [comment]
Brain.exe definitely stopped working there. Thanks!
